name: Build and Push to GHCR

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 1 * *'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./basi_dati_avanzate/mongodb
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mongo-client:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./basi_dati_avanzate/oracledb
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/oracle-client:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
